const idTypeActions = {
    ID_TYPE_LIST: 'ID_TYPE_LIST',
    ID_TYPE_LIST_SUCCESS: 'ID_TYPE_LIST_SUCCESS',
    ID_TYPE_LIST_FAILURE: 'ID_TYPE_LIST_FAILURE',
    ID_TYPE_ADD: 'ID_TYPE_ADD',
    ID_TYPE_ADD_SUCCESS: 'ID_TYPE_ADD_SUCCESS',
    ID_TYPE_ADD_FAILURE: 'ID_TYPE_ADD_FAILURE',
    ID_TYPE_UPDATE: 'ID_TYPE_UPDATE',
    ID_TYPE_UPDATE_SUCCESS: 'ID_TYPE_UPDATE_SUCCESS',
    ID_TYPE_UPDATE_FAILURE: 'ID_TYPE_UPDATE_FAILURE',
    ID_TYPE_DELETE: 'ID_TYPE_DELETE',
    ID_TYPE_DELETE_SUCCESS: 'ID_TYPE_DELETE_SUCCESS',
    ID_TYPE_DELETE_FAILURE: 'ID_TYPE_DELETE_FAILURE',
};

export default idTypeActions;
