const actions = {
    BUSINESS_LIST: 'BUSINESS_LIST',
    BUSINESS_LIST_SUCCESS: 'BUSINESS_LIST_SUCCESS',
    BUSINESS_LIST_FAILURE: 'BUSINESS_LIST_FAILURE',
    BUSINESS_ADD: 'BUSINESS_ADD',
    BUSINESS_ADD_SUCCESS: 'BUSINESS_ADD_SUCCESS',
    BUSINESS_ADD_FAILURE: 'BUSINESS_ADD_FAILURE',
    BUSINESS_UPDATE: 'BUSINESS_UPDATE',
    BUSINESS_UPDATE_SUCCESS: 'BUSINESS_UPDATE_SUCCESS',
    BUSINESS_UPDATE_FAILURE: 'BUSINESS_UPDATE_FAILURE',
    BUSINESS_DELETE: 'BUSINESS_DELETE',
    BUSINESS_DELETE_SUCCESS: 'BUSINESS_DELETE_SUCCESS',
    BUSINESS_DELETE_FAILURE: 'BUSINESS_DELETE_FAILURE',
};

export default actions;
