const actions = {
    AMENITY_LIST: 'AMENITY_LIST',
    AMENITY_LIST_SUCCESS: 'AMENITY_LIST_SUCCESS',
    AMENITY_LIST_FAILURE: 'AMENITY_LIST_FAILURE',
    AMENITY_ADD: 'AMENITY_ADD',
    AMENITY_ADD_SUCCESS: 'AMENITY_ADD_SUCCESS',
    AMENITY_ADD_FAILURE: 'AMENITY_ADD_FAILURE',
    AMENITY_UPDATE: 'AMENITY_UPDATE',
    AMENITY_UPDATE_SUCCESS: 'AMENITY_UPDATE_SUCCESS',
    AMENITY_UPDATE_FAILURE: 'AMENITY_UPDATE_FAILURE',
};

export default actions;
