const actions = {
    ROOMS_LIST: 'ROOMS_LIST',
    ROOMS_LIST_SUCCESS: 'ROOMS_LIST_SUCCESS',
    ROOMS_LIST_FAILURE: 'ROOMS_LIST_FAILURE',
    ROOMS_ADD: 'ROOMS_ADD',
    ROOMS_ADD_SUCCESS: 'ROOMS_ADD_SUCCESS',
    ROOMS_ADD_FAILURE: 'ROOMS_ADD_FAILURE',
    ROOMS_UPDATE: 'ROOMS_UPDATE',
    ROOMS_UPDATE_SUCCESS: 'ROOMS_UPDATE_SUCCESS',
    ROOMS_UPDATE_FAILURE: 'ROOMS_UPDATE_FAILURE',
    ROOMS_DELETE: 'ROOMS_DELETE',
    ROOMS_DELETE_SUCCESS: 'ROOMS_DELETE_SUCCESS',
    ROOMS_DELETE_FAILURE: 'ROOMS_DELETE_FAILURE',
    ROOMS_MULTIPLE_ADD: 'ROOMS_MULTIPLE_ADD',
    ROOMS_MULTIPLE_ADD_SUCCESS: 'ROOMS_MULTIPLE_ADD_SUCCESS',
    ROOMS_MULTIPLE_ADD_FAILURE: 'ROOMS_MULTIPLE_ADD_FAILURE',
    ROOMS_DROPDOWN_LIST: 'ROOMS_DROPDOWN_LIST',
    ROOMS_DROPDOWN_LIST_SUCCESS: 'ROOMS_DROPDOWN_LIST_SUCCESS',
    ROOMS_DROPDOWN_LIST_FAILURE: 'ROOMS_DROPDOWN_LIST_FAILURE',
};

export default actions;
