const actions = {
    COUNTRY_LIST: 'COUNTRY_LIST',
    COUNTRY_LIST_SUCCESS: 'COUNTRY_LIST_SUCCESS',
    COUNTRY_LIST_FAILURE: 'COUNTRY_LIST_FAILURE',
    COUNTRY_ADD: 'COUNTRY_ADD',
    COUNTRY_ADD_SUCCESS: 'COUNTRY_ADD_SUCCESS',
    COUNTRY_ADD_FAILURE: 'COUNTRY_ADD_FAILURE',
    COUNTRY_UPDATE: 'COUNTRY_UPDATE',
    COUNTRY_UPDATE_SUCCESS: 'COUNTRY_UPDATE_SUCCESS',
    COUNTRY_UPDATE_FAILURE: 'COUNTRY_UPDATE_FAILURE',
    COUNTRY_DELETE: 'COUNTRY_DELETE',
    COUNTRY_DELETE_SUCCESS: 'COUNTRY_DELETE_SUCCESS',
    COUNTRY_DELETE_FAILURE: 'COUNTRY_DELETE_FAILURE',
};

export default actions;
