const actions = {
    INQUIRY_LIST: 'INQUIRY_LIST',
    INQUIRY_LIST_SUCCESS: 'INQUIRY_LIST_SUCCESS',
    INQUIRY_LIST_FAILURE: 'INQUIRY_LIST_FAILURE',
    INQUIRY_ADD: 'INQUIRY_ADD',
    INQUIRY_ADD_SUCCESS: 'INQUIRY_ADD_SUCCESS',
    INQUIRY_ADD_FAILURE: 'INQUIRY_ADD_FAILURE',
    INQUIRY_UPDATE: 'INQUIRY_UPDATE',
    INQUIRY_UPDATE_SUCCESS: 'INQUIRY_UPDATE_SUCCESS',
    INQUIRY_UPDATE_FAILURE: 'INQUIRY_UPDATE_FAILURE',
    INQUIRY_DELETE: 'INQUIRY_DELETE',
    INQUIRY_DELETE_SUCCESS: 'INQUIRY_DELETE_SUCCESS',
    INQUIRY_DELETE_FAILURE: 'INQUIRY_DELETE_FAILURE',
};

export default actions;
