const actions = {
    ROOMVIEW_LIST: 'ROOMVIEW_LIST',
    ROOMVIEW_LIST_SUCCESS: 'ROOMVIEW_LIST_SUCCESS',
    ROOMVIEW_LIST_FAILURE: 'ROOMVIEW_LIST_FAILURE',
    ROOMVIEW_ADD: 'ROOMVIEW_ADD',
    ROOMVIEW_ADD_SUCCESS: 'ROOMVIEW_ADD_SUCCESS',
    ROOMVIEW_ADD_FAILURE: 'ROOMVIEW_ADD_FAILURE',
    ROOMVIEW_UPDATE: 'ROOMVIEW_UPDATE',
    ROOMVIEW_UPDATE_SUCCESS: 'ROOMVIEW_UPDATE_SUCCESS',
    ROOMVIEW_UPDATE_FAILURE: 'ROOMVIEW_UPDATE_FAILURE',
    ROOMVIEW_DELETE: 'ROOMVIEW_DELETE',
    ROOMVIEW_DELETE_SUCCESS: 'ROOMVIEW_DELETE_SUCCESS',
    ROOMVIEW_DELETE_FAILURE: 'ROOMVIEW_DELETE_FAILURE',
};

export default actions;
