const actions = {
    MARKETSEGMENT_LIST: 'MARKETSEGMENT_LIST',
    MARKETSEGMENT_LIST_SUCCESS: 'MARKETSEGMENT_LIST_SUCCESS',
    MARKETSEGMENT_LIST_FAILURE: 'MARKETSEGMENT_LIST_FAILURE',
    MARKETSEGMENT_ADD: 'MARKETSEGMENT_ADD',
    MARKETSEGMENT_ADD_SUCCESS: 'MARKETSEGMENT_ADD_SUCCESS',
    MARKETSEGMENT_ADD_FAILURE: 'MARKETSEGMENT_ADD_FAILURE',
    MARKETSEGMENT_UPDATE: 'MARKETSEGMENT_UPDATE',
    MARKETSEGMENT_UPDATE_SUCCESS: 'MARKETSEGMENT_UPDATE_SUCCESS',
    MARKETSEGMENT_UPDATE_FAILURE: 'MARKETSEGMENT_UPDATE_FAILURE',
    MARKETSEGMENT_DELETE: 'MARKETSEGMENT_DELETE',
    MARKETSEGMENT_DELETE_SUCCESS: 'MARKETSEGMENT_DELETE_SUCCESS',
    MARKETSEGMENT_DELETE_FAILURE: 'MARKETSEGMENT_DELETE_FAILURE',
};

export default actions;
