const actions = {
    RESER_LIST: 'RESER_LIST',
    RESER_LIST_SUCCESS: 'RESER_LIST_SUCCESS',
    RESER_LIST_FAILURE: 'RESER_LIST_FAILURE',
    RESER_ADD: 'RESER_ADD',
    RESER_ADD_SUCCESS: 'RESER_ADD_SUCCESS',
    RESER_ADD_FAILURE: 'RESER_ADD_FAILURE',
    RESER_UPDATE: 'RESER_UPDATE',
    RESER_UPDATE_SUCCESS: 'RESER_UPDATE_SUCCESS',
    RESER_UPDATE_FAILURE: 'RESER_UPDATE_FAILURE',
    RESER_DELETE: 'RESER_DELETE',
    RESER_DELETE_SUCCESS: 'RESER_DELETE_SUCCESS',
    RESER_DELETE_FAILURE: 'RESER_DELETE_FAILURE',
    RESER_DROPDOWN_LIST: 'RESER_DROPDOWN_LIST',
    RESER_DROPDOWN_LIST_SUCCESS: 'RESER_DROPDOWN_LIST_SUCCESS',
    RESER_DROPDOWN_LIST_FAILURE: 'RESER_DROPDOWN_LIST_FAILURE',
    AVLBL_ROOM_CATE_LIST: 'AVLBL_ROOM_CATE_LIST',
    AVLBL_ROOM_CAT_SUCCESS: 'AVLBL_ROOM_CAT_SUCCESS',
    AVLBL_ROOM_CAT_FAILURE: 'AVLBL_ROOM_CAT_FAILURE',
};

export default actions;
