const actions = {
    USER_LIST: 'USER_LIST',
    USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USER_LIST_FAILURE: 'USER_LIST_FAILURE',
    USER_ADD: 'USER_ADD',
    USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
    USER_ADD_FAILURE: 'USER_ADD_FAILURE',
    USER_UPDATE: 'USER_UPDATE',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
    USER_DELETE: 'USER_DELETE',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',
};

export default actions;
