const actions = {
    GUEST_LIST: 'GUEST_LIST',
    GUEST_LIST_SUCCESS: 'GUEST_LIST_SUCCESS',
    GUEST_LIST_FAILURE: 'GUEST_LIST_FAILURE',
    GUEST_ADD: 'GUEST_ADD',
    GUEST_ADD_SUCCESS: 'GUEST_ADD_SUCCESS',
    GUEST_ADD_FAILURE: 'GUEST_ADD_FAILURE',
    GUEST_UPDATE: 'GUEST_UPDATE',
    GUEST_UPDATE_SUCCESS: 'GUEST_UPDATE_SUCCESS',
    GUEST_UPDATE_FAILURE: 'GUEST_UPDATE_FAILURE',
    GUEST_DELETE: 'GUEST_DELETE',
    GUEST_DELETE_SUCCESS: 'GUEST_DELETE_SUCCESS',
    GUEST_DELETE_FAILURE: 'GUEST_DELETE_FAILURE',
};

export default actions;
