const actions = {
    BOOKING_LIST: 'BOOKING_LIST',
    BOOKING_LIST_SUCCESS: 'BOOKING_LIST_SUCCESS',
    BOOKING_LIST_FAILURE: 'BOOKING_LIST_FAILURE',
    BOOKING_ADD: 'BOOKING_ADD',
    BOOKING_ADD_SUCCESS: 'BOOKING_ADD_SUCCESS',
    BOOKING_ADD_FAILURE: 'BOOKING_ADD_FAILURE',
    BOOKING_UPDATE: 'BOOKING_UPDATE',
    BOOKING_UPDATE_SUCCESS: 'BOOKING_UPDATE_SUCCESS',
    BOOKING_UPDATE_FAILURE: 'BOOKING_UPDATE_FAILURE',
    BOOKING_DELETE: 'BOOKING_DELETE',
    BOOKING_DELETE_SUCCESS: 'BOOKING_DELETE_SUCCESS',
    BOOKING_DELETE_FAILURE: 'BOOKING_DELETE_FAILURE',
};

export default actions;
