const actions = {
    ROOMCATEGORY_LIST: 'ROOMCATEGORY_LIST',
    ROOMCATEGORY_LIST_SUCCESS: 'ROOMCATEGORY_LIST_SUCCESS',
    ROOMCATEGORY_LIST_FAILURE: 'ROOMCATEGORY_LIST_FAILURE',
    ROOMCATEGORY_ADD: 'ROOMCATEGORY_ADD',
    ROOMCATEGORY_ADD_SUCCESS: 'ROOMCATEGORY_ADD_SUCCESS',
    ROOMCATEGORY_ADD_FAILURE: 'ROOMCATEGORY_ADD_FAILURE',
    ROOMCATEGORY_UPDATE: 'ROOMCATEGORY_UPDATE',
    ROOMCATEGORY_UPDATE_SUCCESS: 'ROOMCATEGORY_UPDATE_SUCCESS',
    ROOMCATEGORY_UPDATE_FAILURE: 'ROOMCATEGORY_UPDATE_FAILURE',
    ROOMCATEGORY_DELETE: 'ROOMCATEGORY_DELETE',
    ROOMCATEGORY_DELETE_SUCCESS: 'ROOMCATEGORY_DELETE_SUCCESS',
    ROOMCATEGORY_DELETE_FAILURE: 'ROOMCATEGORY_DELETE_FAILURE',
};

export default actions;
