const actions = {
    CITY_LIST: 'CITY_LIST',
    CITY_LIST_SUCCESS: 'CITY_LIST_SUCCESS',
    CITY_LIST_FAILURE: 'CITY_LIST_FAILURE',
    CITY_ADD: 'CITY_ADD',
    CITY_ADD_SUCCESS: 'CITY_ADD_SUCCESS',
    CITY_ADD_FAILURE: 'CITY_ADD_FAILURE',
    CITY_UPDATE: 'CITY_UPDATE',
    CITY_UPDATE_SUCCESS: 'CITY_UPDATE_SUCCESS',
    CITY_UPDATE_FAILURE: 'CITY_UPDATE_FAILURE',
    CITY_DELETE: 'CITY_DELETE',
    CITY_DELETE_SUCCESS: 'CITY_DELETE_SUCCESS',
    CITY_DELETE_FAILURE: 'CITY_DELETE_FAILURE',
};

export default actions;
