const actions = {
    PAY_TYP_LIST: 'PAY_TYP_LIST',
    PAY_TYP_LIST_SUCCESS: 'PAY_TYP_LIST_SUCCESS',
    PAY_TYP_LIST_FAILURE: 'PAY_TYP_LIST_FAILURE',
    PAY_TYP_ADD: 'PAY_TYP_ADD',
    PAY_TYP_ADD_SUCCESS: 'PAY_TYP_ADD_SUCCESS',
    PAY_TYP_ADD_FAILURE: 'PAY_TYP_ADD_FAILURE',
    PAY_TYP_UPD: 'PAY_TYP_UPD',
    PAY_TYP_UPD_SUCCESS: 'PAY_TYP_UPD_SUCCESS',
    PAY_TYP_UPD_FAILURE: 'PAY_TYP_UPD_FAILURE',
    PAY_TYP_DEL: 'PAY_TYP_DEL',
    PAY_TYP_DEL_SUCCESS: 'PAY_TYP_DEL_SUCCESS',
    PAY_TYP_DEL_FAILURE: 'PAY_TYP_DEL_FAILURE',
};

export default actions;
