const actions = {
    SECTION_LIST: 'SECTION_LIST',
    SECTION_LIST_SUCCESS: 'SECTION_LIST_SUCCESS',
    SECTION_LIST_FAILURE: 'SECTION_LIST_FAILURE',
    SECTION_ADD: 'SECTION_ADD',
    SECTION_ADD_SUCCESS: 'SECTION_ADD_SUCCESS',
    SECTION_ADD_FAILURE: 'SECTION_ADD_FAILURE',
    SECTION_UPDATE: 'SECTION_UPDATE',
    SECTION_UPDATE_SUCCESS: 'SECTION_UPDATE_SUCCESS',
    SECTION_UPDATE_FAILURE: 'SECTION_UPDATE_FAILURE',
    SECTION_DELETE: 'SECTION_DELETE',
    SECTION_DELETE_SUCCESS: 'SECTION_DELETE_SUCCESS',
    SECTION_DELETE_FAILURE: 'SECTION_DELETE_FAILURE',
};

export default actions;
