const actions = {
    FLOOR_LIST: 'FLOOR_LIST',
    FLOOR_LIST_SUCCESS: 'FLOOR_LIST_SUCCESS',
    FLOOR_LIST_FAILURE: 'FLOOR_LIST_FAILURE',
    FLOOR_ADD: 'FLOOR_ADD',
    FLOOR_ADD_SUCCESS: 'FLOOR_ADD_SUCCESS',
    FLOOR_ADD_FAILURE: 'FLOOR_ADD_FAILURE',
    FLOOR_UPDATE: 'FLOOR_UPDATE',
    FLOOR_UPDATE_SUCCESS: 'FLOOR_UPDATE_SUCCESS',
    FLOOR_UPDATE_FAILURE: 'FLOOR_UPDATE_FAILURE',
    FLOOR_DELETE: 'FLOOR_DELETE',
    FLOOR_DELETE_SUCCESS: 'FLOOR_DELETE_SUCCESS',
    FLOOR_DELETE_FAILURE: 'FLOOR_DELETE_FAILURE',
};

export default actions;
