const actions = {
    BOOKINGINQ_LIST: 'BOOKINGINQ_LIST',
    BOOKINGINQ_LIST_SUCCESS: 'BOOKINGINQ_LIST_SUCCESS',
    BOOKINGINQ_LIST_FAILURE: 'BOOKINGINQ_LIST_FAILURE',
    BOOKINGINQ_ADD: 'BOOKINGINQ_ADD',
    BOOKINGINQ_ADD_SUCCESS: 'BOOKINGINQ_ADD_SUCCESS',
    BOOKINGINQ_ADD_FAILURE: 'BOOKINGINQ_ADD_FAILURE',
    BOOKINGINQ_UPDATE: 'BOOKINGINQ_UPDATE',
    BOOKINGINQ_UPDATE_SUCCESS: 'BOOKINGINQ_UPDATE_SUCCESS',
    BOOKINGINQ_UPDATE_FAILURE: 'BOOKINGINQ_UPDATE_FAILURE',
    BOOKINGINQ_DELETE: 'BOOKINGINQ_DELETE',
    BOOKINGINQ_DELETE_SUCCESS: 'BOOKINGINQ_DELETE_SUCCESS',
    BOOKINGINQ_DELETE_FAILURE: 'BOOKINGINQ_DELETE_FAILURE',
    BOOKINGINQ_DROPDOWN_LIST: 'BOOKINGINQ_DROPDOWN_LIST',
    BOOKINGINQ_DROPDOWN_LIST_SUCCESS: 'BOOKINGINQ_DROPDOWN_LIST_SUCCESS',
    BOOKINGINQ_DROPDOWN_LIST_FAILURE: 'BOOKINGINQ_DROPDOWN_LIST_FAILURE',
};

export default actions;
