const actions = {
    STATE_LIST: 'STATE_LIST',
    STATE_LIST_SUCCESS: 'STATE_LIST_SUCCESS',
    STATE_LIST_FAILURE: 'STATE_LIST_FAILURE',
    STATE_ADD: 'STATE_ADD',
    STATE_ADD_SUCCESS: 'STATE_ADD_SUCCESS',
    STATE_ADD_FAILURE: 'STATE_ADD_FAILURE',
    STATE_UPDATE: 'STATE_UPDATE',
    STATE_UPDATE_SUCCESS: 'STATE_UPDATE_SUCCESS',
    STATE_UPDATE_FAILURE: 'STATE_UPDATE_FAILURE',
    STATE_DELETE: 'STATE_DELETE',
    STATE_DELETE_SUCCESS: 'STATE_DELETE_SUCCESS',
    STATE_DELETE_FAILURE: 'STATE_DELETE_FAILURE',
    STATE_DROPDOWN_LIST: 'STATE_DROPDOWN_LIST',
    STATE_DROPDOWN_LIST_SUCCESS: 'STATE_DROPDOWN_LIST_SUCCESS',
    STATE_DROPDOWN_LIST_FAILURE: 'STATE_DROPDOWN_LIST_FAILURE',
};

export default actions;
