const actions = {
    SALESPERSON_LIST: 'SALESPERSON_LIST',
    SALESPERSON_LIST_SUCCESS: 'SALESPERSON_LIST_SUCCESS',
    SALESPERSON_LIST_FAILURE: 'SALESPERSON_LIST_FAILURE',
    SALESPERSON_ADD: 'SALESPERSON_ADD',
    SALESPERSON_ADD_SUCCESS: 'SALESPERSON_ADD_SUCCESS',
    SALESPERSON_ADD_FAILURE: 'SALESPERSON_ADD_FAILURE',
    SALESPERSON_UPDATE: 'SALESPERSON_UPDATE',
    SALESPERSON_UPDATE_SUCCESS: 'SALESPERSON_UPDATE_SUCCESS',
    SALESPERSON_UPDATE_FAILURE: 'SALESPERSON_UPDATE_FAILURE',
    SALESPERSON_DELETE: 'SALESPERSON_DELETE',
    SALESPERSON_DELETE_SUCCESS: 'SALESPERSON_DELETE_SUCCESS',
    SALESPERSON_DELETE_FAILURE: 'SALESPERSON_DELETE_FAILURE',
};

export default actions;
