const actions = {
    CP_LIST: 'CP_LIST',
    CP_LIST_SUCCESS: 'CP_LIST_SUCCESS',
    CP_LIST_FAILURE: 'CP_LIST_FAILURE',
    CP_ADD: 'CP_ADD',
    CP_ADD_SUCCESS: 'CP_ADD_SUCCESS',
    CP_ADD_FAILURE: 'CP_ADD_FAILURE',
    CP_UPDATE: 'CP_UPDATE',
    CP_UPDATE_SUCCESS: 'CP_UPDATE_SUCCESS',
    CP_UPDATE_FAILURE: 'CP_UPDATE_FAILURE',
    CP_DELETE: 'CP_DELETE',
    CP_DELETE_SUCCESS: 'CP_DELETE_SUCCESS',
    CP_DELETE_FAILURE: 'CP_DELETE_FAILURE',
};

export default actions;
