const actions = {
    TNC_LIST: 'TNC_LIST',
    TNC_LIST_SUCCESS: 'TNC_LIST_SUCCESS',
    TNC_LIST_FAILURE: 'TNC_LIST_FAILURE',
    TNC_ADD: 'TNC_ADD',
    TNC_ADD_SUCCESS: 'TNC_ADD_SUCCESS',
    TNC_ADD_FAILURE: 'TNC_ADD_FAILURE',
    TNC_UPDATE: 'TNC_UPDATE',
    TNC_UPDATE_SUCCESS: 'TNC_UPDATE_SUCCESS',
    TNC_UPDATE_FAILURE: 'TNC_UPDATE_FAILURE',
    TNC_DELETE: 'TNC_DELETE',
    TNC_DELETE_SUCCESS: 'TNC_DELETE_SUCCESS',
    TNC_DELETE_FAILURE: 'TNC_DELETE_FAILURE',
};

export default actions;
