const actions = {
    ROOMPLAN_LIST: 'ROOMPLAN_LIST',
    ROOMPLAN_LIST_SUCCESS: 'ROOMPLAN_LIST_SUCCESS',
    ROOMPLAN_LIST_FAILURE: 'ROOMPLAN_LIST_FAILURE',
    ROOMPLAN_ADD: 'ROOMPLAN_ADD',
    ROOMPLAN_ADD_SUCCESS: 'ROOMPLAN_ADD_SUCCESS',
    ROOMPLAN_ADD_FAILURE: 'ROOMPLAN_ADD_FAILURE',
    ROOMPLAN_UPDATE: 'ROOMPLAN_UPDATE',
    ROOMPLAN_UPDATE_SUCCESS: 'ROOMPLAN_UPDATE_SUCCESS',
    ROOMPLAN_UPDATE_FAILURE: 'ROOMPLAN_UPDATE_FAILURE',
};

export default actions;
